# crc: crc.o 
# 	g++ -pthread crc.o -o crc
# crc.o: crc.cpp
# 	g++ -pthread -c crc.cpp

# crsd: crsd.o 
# 	g++ crsd.o -o crsd
# crsd.o: crsd.cpp
# 	g++ -c crsd.cpp

# clean:
# 	rm *.o crc crsd

compile:
	g++  -pthread crc.cpp -o crc
	g++   crsd.cpp -o crsd